// <auto-generated />
using ListOfInstitutions.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ListOfInstitutions.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211129080803_AddDataSeedings")]
    partial class AddDataSeedings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ListOfInstitutions.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nigeria",
                            ShortName = "NG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United State Of America",
                            ShortName = "USA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "South Africa",
                            ShortName = "SA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Canada",
                            ShortName = "CA"
                        });
                });

            modelBuilder.Entity("ListOfInstitutions.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "FCT, Abuja",
                            CountryId = 1,
                            Name = "Open University",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cambridge",
                            CountryId = 2,
                            Name = "Massachusetts Institute of Technology",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Preller St, Muckleneuk, Pretoria, 0002, South Africa",
                            CountryId = 3,
                            Name = "University of South Africa",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ontario, Canada",
                            CountryId = 4,
                            Name = "University of Toronto",
                            Rating = 5.4000000000000004
                        });
                });

            modelBuilder.Entity("ListOfInstitutions.Models.School", b =>
                {
                    b.HasOne("ListOfInstitutions.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
